image: Ubuntu
stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-order.jar &
  - java -jar ./artifacts/webdrivermanager-5.2.3-fat.jar <args>

build_script:
  - chmod +x gradlew
  - ./gradlew test --info